---
name: "Better Mark Watched"
guid: "d14e432b-2bc8-4ebf-bc41-a9082cbba0ef"
version: "1.0.0.0"
targetAbi: "10.8.0.0"
framework: "net6.0"
overview: "Short description about your plugin"
description: >
  This is a longer description that can span more than one
  line and include details about your plugin.
category: "General"
owner: "jellyfin"
artifacts:
- "q12.JellyfinPlugin.BetterMarkWatched.dll"
changelog: >
  changelog
